url: https://y7kim.github.io
baseurl: /one-stop-realtor.github.io

# Site settings
title: One Stop Realtor
email: onestoprealtor001@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
# - name: Kay Garland
#   pic: 1
#   position: Lead Designer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

- name: Varoon Ravi
  pic: 4
  position: Founder - Techie - Realtor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/VaroonRavi
    - title: linkedin
      url: https://in.linkedin.com/in/varoon-ravi-7b3214112

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url: https://www.facebook.com/VaroonRavi
  - title: stack-overflow
    url: #
  - title: bitbucket
    url: #
  - title: github
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: \#199, 6th Cross, 28th Main, Sector - 1
  - line: H.S.R Layout, Bangalore 560102

# Build settings
markdown: kramdown
permalink: pretty